CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (id int NOT NULL AUTO_INCREMENT,
   burger_name VARCHAR(40) NOT NULL,
   devoured BOOLEAN DEFAULT 0,
   createdDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(id)
 );
